### ISSUE TITLE
Feature request: Add typings for methods

### ISSUE THREAD

**Issue by yashmahalwal** [datavis-tech/graph-data-structure#24]
I needed a simple library that implemented Graph DS. Other libraries that I came across were either too basic or were an overkill with visualisation tools and so on. I have been able to integrate the library into my code base but a constant pain point is lack of typings.

For now, I work with //@ts-ignore. But I believe that adding typings would help in seamless integration in scalable code bases.

**Comment by curran** [comment]
PRs welcome!

**Comment by yashmahalwal** [comment]
@curran  I had a bit of time on my hand today and I migrated the codebase [under this PR](https://github.com/datavis-tech/graph-data-structure/pull/26). Please review the changes.

**Comment by yashmahalwal** [comment]
It was really awesome of you to merge the PR. I updated the package in my project today. The current version is 1.10.0 . But no typedefs were shipped with the npm package. Maybe something with the .npmignore?

PS: the package.json on github still points to 1.9.0. Maybe you did not commit after releasing?

**Comment by curran** [comment]
@yashmahalwal Thanks for the notes! I will clean this up.

**Comment by curran** [comment]
Addressed these issues and released in https://github.com/datavis-tech/graph-data-structure/releases/tag/v1.12.0 .

Please give this version a try. Thanks!

**Comment by yashmahalwal** [comment]
Yeah that fixes stuff (y)

**Comment by curran** [comment]
Hooray!
