### ISSUE TITLE
shortestPath does not return the total weight over all edges in the path

### ISSUE THREAD

**Issue by skeletorkun** [datavis-tech/graph-data-structure#25]
https://www.npmjs.com/package/graph-data-structure#shortest-path

example : 
```
        let shortestPath = graph.shortestPath(departure, arrival);
        console.log("shortest path " + JSON.stringify(shortestPath));
```

Expected behavior: 

> The returned array also contains a weight property, which is the total weight over all edges in the path

Actual behavior: 
`shortest path ["Hoth","Endor"]`

**Comment by skeletorkun** [comment]
Nevermind. it does actually.
```
let shortestPath = graph.shortestPath(departure, arrival);
console.log("shortest path total weight " + shortestPath.weight);
```

**Comment by curran** [comment]
Thanks for reporting your experience!
