### ISSUE TITLE
topologicalSort produces invalid results for graphs with cycles

### ISSUE THREAD

**Issue by notmatthancock** [datavis-tech/graph-data-structure#41]
Performing a topological sort on a graph with cycles should throw an error (related: https://github.com/datavis-tech/graph-data-structure/issues/32).

Currently, you can do:

```javascript
g = Graph()
g.addEdge('a', 'b').addEdge('b', 'a').topologicalSort()
// => [ 'a', 'b' ]
```

**Comment by curran** [comment]
I agree an error should be thrown.

>A topological ordering is possible if and only if the graph has no directed cycles, that is, if it is a directed acyclic graph (DAG).

From https://en.wikipedia.org/wiki/Topological_sorting

I wonder what sort of change this would take...

**Comment by notmatthancock** [comment]
It seems the depth first function could be slightly modified to be in accordance with the method shown on wiki so that it throws an Error on a detected cycle -- maybe only if a `errorOnCycle` flag is passed to `depthFirstSearch`?

**Comment by curran** [comment]
Got it. That would be a welcome change!

**Comment by notmatthancock** [comment]
Cool, I'll take a whack at it.
