### ISSUE TITLE
Topological sort type doesn't allow for not passing in a source node

### ISSUE THREAD

**Issue by CrispyBacon1999** [datavis-tech/graph-data-structure#49]
In the `index.d.ts` file, topologicalSort is defined with `sourceNodes: NodeId[]`, which doesn't allow for not passing in any source nodes. This makes following the examples impossible, and as far as I can tell, there's no easy way to actually make it run without the source nodes being passed in without chaning the `index.d.ts` to be `sourceNodes?[]`

**Comment by curran** [comment]
Oh interesting! Sorry about that.

Would you be open to contributing a change to the type definitions to allow for this case?

**Comment by CrispyBacon1999** [comment]
For sure, just put in #50, which should fix it.
