### ISSUE TITLE
Installation fails because binary dist/cli.module.js is missing

### ISSUE THREAD

**Issue by uwej711** [datavis-tech/graph-data-structure#59]
Hi, when running a package (renovate) that requires this module (maybe through other dependencies) with npx we receive the error:
enoent ENOENT: no such file or directory, chmod '/home/vagrant/.npm/_npx/1665/lib/node_modules/renovate/node_modules/graph-data-structure/dist/cli.module.js'
Your package.json contains an entry for a binary "dist/cli.module.js" that is not part of the npm package.
I'm no export here, but either that file should be there or the bin entry removed from your package.json?

**Comment by curran** [comment]
Oh interesting... Yeah sorry about that!

**Comment by curran** [comment]
Published fix in https://github.com/datavis-tech/graph-data-structure/releases/tag/v3.1.1

Hope it makes it work for you!
