### ISSUE TITLE
Default export in package.json not being last is triggering a webpack error

### ISSUE THREAD

**Issue by cbranch101** [datavis-tech/graph-data-structure#64]
```json 
"exports": {
    "require": "./dist/index.cjs",
    "default": "./dist/index.modern.js",
    "types": "./dist/index.d.ts"
},
```

webpack and node want the default the key to be last

**Comment by curran** [comment]
How to reproduce the error/warning?

I would welcome a PR for a fix if you'd like to take a stab at it.

**Comment by flleonx** [comment]
I got the same error

![image](https://user-images.githubusercontent.com/69682697/229397206-45a2015f-c142-4aef-a4ef-c06c54b3a889.png)

**Comment by rtlastra** [comment]
I got the same error

**Comment by curran** [comment]
Released fix in https://github.com/datavis-tech/graph-data-structure/releases/tag/v3.3.0

Please let me know if this solves the issue for you. Thanks!

**Comment by curran** [comment]
Released.
