### ISSUE TITLE
How to require the library

### ISSUE THREAD

**Issue by sebastianarena** [datavis-tech/graph-data-structure#72]
Hello, I use this library in plain NodeJs.
The way to import it properly is:

```
const { Graph } = require('graph-data-structure')
```

Your documentation just says:

```
var Graph = require('graph-data-structure')
```

Which then fails when trying to call Graph().

Thank you for this awesome library!

PS: 3.4.0 is not showing up in NPM at the moment, just 3.3.0

**Comment by curran** [comment]
Nice catch! I'd welcome a PR for the README.
