### ISSUE TITLE
Publish Release Candidate for v4 to NPM

### ISSUE THREAD

**Issue by curran** [datavis-tech/graph-data-structure#85]
I'd like to do one of those fancy "release candidate" releases on NPM so we can iterate the next major version release a few times to work out the kinks before we actually publish the v4 release to NPM. I've never done this but I've seen it done.

**Comment by curran** [comment]
Some insights from ChatGPT:

To publish a release candidate (RC) to NPM, you can follow these steps:

1. **Update the Version Number:**
   - Use semantic versioning with a `-rc.X` suffix, where `X` is the release candidate version number.
   - For example, if the current version is `1.0.0`, your RC version might be `1.0.1-rc.0`.

   You can update the version manually in the `package.json` or use npm commands:
   ```bash
   npm version prerelease --preid=rc
   ```
   This will automatically increment the version to the next prerelease version with an `rc` tag.

2. **Publish the Release Candidate:**
   - Use the `--tag` option to specify that this is a release candidate. This prevents the release candidate from being installed by default when someone runs `npm install <package>` without specifying a version.
   
   ```bash
   npm publish --tag rc
   ```

3. **Install the Release Candidate:**
   - Users who want to test the release candidate can install it by specifying the `rc` tag:
   
   ```bash
   npm install <package>@rc
   ```

4. **Promote the RC to Latest (Optional):**
   - If the release candidate is stable and ready to be promoted to the latest version, you can either republish it without the `--tag` or update the version and publish normally.

   ```bash
   npm dist-tag add <package>@<version> latest
   ```
   or
   ```bash
   npm publish
   ```

### Example Workflow
1. Update the version to `1.0.1-rc.0`:
   ```bash
   npm version prerelease --preid=rc
   ```

2. Publish the release candidate:
   ```bash
   npm publish --tag rc
   ```

3. If everything is good and you want to promote it:
   ```bash
   npm dist-tag add <package>@1.0.1-rc.0 latest
   ```

This process allows you to release a version for testing without affecting the stable version used by most users.

**Comment by JesusTheHun** [comment]
Do you think you can do that in the near future ?
If you're a bit scared about this RC thing, you can make your tests under a new package name. 
Publish the version `3.5.0` of the package `graph-data-structure-xyz`, then try to publish the RC version of that package.

Once you are done, you can delete the package altogether. Beware though, you have 48h after the creation to do so IIRC.

**Comment by curran** [comment]
I fiddled with the prerelease stuff for a while but just decided to go ahead and publish v4!

https://github.com/datavis-tech/graph-data-structure/releases/tag/v4.0.0

It's live now on NPM. Would you be able to please test it out in your workflow and see if everything looks good? Thanks!

**Comment by JesusTheHun** [comment]
@curran I just did ! It works like a charm ✨🎉

**Comment by JesusTheHun** [comment]
@curran now one must update the README to reflect the new version's API :D

**Comment by curran** [comment]
Indeed!

https://github.com/datavis-tech/graph-data-structure/issues/90
