### ISSUE TITLE
Rename type check command to something else than "tsc" to avoid confusion.

### ISSUE THREAD

**Issue by JesusTheHun** [datavis-tech/graph-data-structure#88]
`tsc` is a command in itself. Having to run `npm run tsc` can be confusing. 
The previous name `type-check` was a better fit IMHO. In my projects I use `ts-check`, which is pretty much the same.
The command itself should stay the same.

**Comment by curran** [comment]
Sure, either way. It's just a convention I use in all my projects nowadays. We can rename it back.
