### ISSUE TITLE
Change serialization to use objects for nodes

### ISSUE THREAD

**Issue by curran** [datavis-tech/graph-data-structure#9]
Make the structure be like this:

```json
var nodes = [
  {"id": "Alice"},
  {"id": "Bob"},
  {"id": "Carol"}
];

var links = [
  {"source": "Alice", "target": "Bob"},
  {"source": "Bob", "target": "Carol"}
];
```

 * [x] Serialization
 * [x] Deserialization
 * [ ] Update docs

**Comment by curran** [comment]
Related to https://github.com/d3/d3-force/issues/32

**Comment by curran** [comment]
Required for https://github.com/datavis-tech/reactive-model/issues/28

**Comment by curran** [comment]
Part of reactive-model 1.0 https://github.com/datavis-tech/reactive-model/issues/31

**Comment by Natallia112202** [comment]
The structure of my file with links and nodes perfectly matches the one recommended in this blog:
{
  "nodes": [
    { "id": "a" },
    { "id": "b" },
    { "id": "c" }
  ],
  "links": [
    { "source": "a", "target": "b" },
    { "source": "b", "target": "c" }
  ]
}
Yet, when I run my index.html file (attached) using graph_russian.json file (attached) I got the "Cannot create property 'vx' on string" error.
  Can anyone help?


[graph_russian.txt](https://github.com/datavis-tech/graph-data-structure/files/1456360/graph_russian.txt)
[index.txt](https://github.com/datavis-tech/graph-data-structure/files/1456361/index.txt)

**Comment by curran** [comment]
This seems like a question about D3, not about this library.

Please post your request for D3 help in the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or the [d3-js Slack](https://d3js.slack.com/).
